import { IAddress } from "./address";
import { ICustomer } from "./customer";
import { IDiscountApplication } from "./discountApplication";
import { ILineItem } from "./lineItem";
import { IShippingMethod } from "./shippingMethod";
import { ITaxLine } from "./taxLine";
import { ITransaction } from "./transaction";

export interface IOrder {
  attributes: any;
  billing_address: IAddress;
  cancel_reason: string;
  cancel_reason_label: string;
  cancelled: boolean;
  cancelled_at: string;
  cart_level_discount_applications: IDiscountApplication[];
  confirmation_number: string;
  created_at: string;
  customer: ICustomer;
  customer_order_url: string;
  customer_url: string;
  discount_applications: IDiscountApplication[];
  email: string;
  financial_status: string;
  financial_status_label: string;
  fulfillment_status: string;
  fulfillment_status_label: string;
  id: number;
  item_count: number;
  line_items: ILineItem[];
  line_items_subtotal_price: number;
  metafields: any;
  name: string;
  note: string;
  order_number: number;
  order_status_url: string;
  phone: string;
  pickup_in_store: boolean;
  shipping_address: IAddress;
  shipping_methods: IShippingMethod[];
  shipping_price: number;
  subtotal_line_items: ILineItem[];
  subtotal_price: number;
  tags: string[];
  tax_lines: ITaxLine[];
  tax_price: number;
  total_discounts: number;
  total_duties: number;
  total_net_amount: number;
  total_price: number;
  total_refunded_amount: number;
  transactions: ITransaction[];
}
