import { ICollection } from "./collection";
import { IImage } from "./image";
import { IMedia } from "./media";
import { IMetafield } from "./metafield";
import { IProductOption } from "./productOption";
import { ISellingPlan } from "./sellingPlan";
import { ISellingPlanAllocation } from "./sellingPlanAllocation";
import { ISellingPlanGroup } from "./sellingPlanGroup";
import { ITaxonomyCategory } from "./taxonomyCategoryName";
import { IVariant } from "./variant";

export interface IProduct {
  available: boolean;
  category: ITaxonomyCategory;
  collections: ICollection[];
  compare_at_price: number;
  compare_at_price_max: number;
  compare_at_price_min: number;
  compare_at_price_varies: boolean;
  content: string;
  created_at: string;
  description: string;
  featured_image: IImage;
  featured_media: IMedia;
  first_available_variant: IVariant;
  gift_card?: boolean;
  handle: string;
  has_only_default_variant: boolean;
  id: number;
  images: IImage[];
  media: IMedia[];
  metafields: IMetafield[];
  options: string[];
  options_by_name: any;
  options_with_values: IProductOption[];
  price: number;
  price_max: number;
  price_min: number;
  price_varies: boolean;
  published_at: string;
  quantity_price_breaks_configured?: boolean;
  requires_selling_plan: boolean;
  selected_or_first_available_selling_plan_allocation: ISellingPlanAllocation;
  selected_or_first_available_variant: IVariant;
  selected_selling_plan: ISellingPlan;
  selected_selling_plan_allocation: ISellingPlanAllocation;
  selected_variant: IVariant;
  selling_plan_groups: ISellingPlanGroup[];
  tags: string[];
  template_suffix: string;
  title: string;
  type: string;
  url: string;
  variants: IVariant[];
  vendor: string;
}
